#server:
#  port: 8888
spring:
  main:
    web-application-type: none
  datasource:
    url: ######:3306/block?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&autoReconnect=true&failOverReadOnly=false
    username: ######
    password: ######
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 60000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 60
      minimum-idle: 10
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
    open-in-view: true
  redis:
    host: ##.###.###.#
    port: 6379
    password: ######
  elasticsearch:
    jest:
      uris: http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###
elasticsearch.uris.http: http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###,http://##.###.###.###:###

redis:
  key:
    macdSignal: stock_market_macd_signaling

es:
  index:
    macdData: stock_market_macd_data
    macdSignal: stock_market_macd_result
    macdExpectedPrice: stock_market_macd_expected_price
    macdResonance: stock_market_macd_resonance

kLineDifference_4: 4
kLineDifference_7: 7

email:
  address:
  
